### ISSUE TITLE
Add ability to suppress pageview event

### ISSUE THREAD

**Issue by paracycle** [bgarret/google-analytics-rails#24]
There are some cases (especially in single page apps) where it is not desirable to automatically send a `pageview` event at library initialization. For those cases, we need a way to suppress this event in `analytics_init`.

**Comment by viperdezigns** [comment]
https://github.com/viperdezigns/google-analytics-rails/commit/6b11d0f55ce266734f5c992adf4ae743d89a1965#diff-a3cc964f0b9227c7988342dcb9d2a935R104

PR #26

**Comment by spodlecki** [comment]
merged into master, `1.0.0` (universal analytics, though)

Pass option: `skip_pageview: true` to the init
