### ISSUE TITLE
Using UserId from Analytics

### ISSUE THREAD

**Issue by rafaelcgo** [bgarret/google-analytics-rails#25]
What's the best way to use the User Id feature from analytics with this gem?

https://developers.google.com/analytics/devguides/collection/analyticsjs/user-id

**Comment by scarver2** [comment]
+1

The google-analytics-rails gem is not yielding passed-in user ID variable which is a requirement for this task.

````ruby
analytics_init(uid: '1')
```` 

should yield `ga('create', 'UA-XXXXX-Y', { 'uid': '1'});`, but it doesn't.

CITE: https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#user_id

**Comment by spodlecki** [comment]
@scarver2 @rafaelcgo 

Take a look at the PR, https://github.com/bgarret/google-analytics-rails/pull/30, and let me know if this is what you're after.

**Comment by spodlecki** [comment]
Merged in PR, closing issue
