### ISSUE TITLE
enable ga('require', 'displayfeatures');?

### ISSUE THREAD

**Issue by gamesover** [bgarret/google-analytics-rails#39]
Does this gem support https://developers.google.com/analytics/devguides/collection/analyticsjs/display-features?

**Comment by spodlecki** [comment]
This gem doesn't usually tap directly into features -- but it'll give you the building blocks.

```ruby
# ... somewhere in your code
displayfeatures = GA::Events::Require.new('displayfeatures')
# ...

# Rails View Helper
analytics_init(custom_vars: [displayfeatures])
```
_disclaimer: I didn't test this_

**Comment by spodlecki** [comment]
@gamesover did this suggestion work out for you?

**Comment by gamesover** [comment]
Sorry, I did not use this gem in the end.
