### ISSUE TITLE
Rails 5 Web Services Application: Lite version

### ISSUE THREAD

**Issue by dbeqiraj** [bgarret/google-analytics-rails#43]
I have a Rails 5 application which serves only as an API provider and executes some background jobs.
I want to know if Google Analytics offers support for these kind of applications where there is no file like:

`app/views/layout/application.html.erb`

Where am I supposed to put this line of code in that case:

`<%= analytics_init if GoogleAnalytics.valid_tracker? %>`

**Comment by spodlecki** [comment]
If your Rails app serves as an API Layer only, this layer wouldn't be concerned with anything front-end javascript... yes?

**Comment by spodlecki** [comment]
so, the short answer is -- you probably should not be using this JS focused gem in an API Layer. There are ways you can run google analytics server side, but not in this gem.

The long answer is, if you really wanted to, you could respond with the analytics in json and do an eval in javascript... I'd suggest placing the GA concern in the front-end app, though.
