### ISSUE TITLE
Anonymize IP for GDPR?

### ISSUE THREAD

**Issue by parterburn** [bgarret/google-analytics-rails#44]
How/where would we add the `ga('set', 'anonymizeIp', true);` from https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp to comply with GDPR?

**Comment by spodlecki** [comment]
If you're using the view helper,

```
=analytics_init(anonymize: true)
```

If you're building your own list of events,

```
events.unshift GA::Events::AnonymizeIp.new
```
